language: erlang
script: "GPROC_DIST=true rebar get-deps compile eunit"
otp_release:
    - 22.0.2
    - 21.0.1
    - 20.3
    - 19.3
    - 19.0
    - 18.3
    - 18.2.1
    - 18.2
    - 18.1
    - 18.0
